
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:16.2
    environment:
      - POSTGRES_DB=shame
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=moi
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
