### Create a shame
POST {{host}}/create-shame
Content-Type: application/json
Accept: application/json

{"name": "pipou", "status": "Assembling"}

> {%
    client.test("Request executed", () => {
        client.assert(response.status === 201);
    })
 %}
###
GET {{host}}/list-shame
Accept: application/json

> {%
    client.test("Request executed", () => {
        client.assert(response.status === 200);
    })
%}